# Generated by Django 3.2.5 on 2021-08-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cost',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
